# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - develop
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Notification
        uses: erguotou520/instant-access-action@0.0.3
        if: ${{ success() }}
        with:
          channel: 'd255d62caef24a3bb66c3465dad70407'
          head: '{{branchName}}部署完成'
          body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
      - name: Notification
        uses: erguotou520/instant-access-action@0.0.3
        if: ${{ failure() }}
        with:
          channel: 'd255d62caef24a3bb66c3465dad70407'
          head: '{{branchName}}部署失败'
          body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
